project:
  type: website
  output-dir: docs

website:
  title: "Chethana's Portfolio"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme:
      light: sandstone
      dark: cyborg
    css: styles.css
    toc: true
    include-after-body: script.js

editor: visual
